INSERT INTO personal(emp_id,nombre,apellido,depto,emp_code) VALUES('1','Jose Luis','Mamani','Administracion','1');
INSERT INTO personal(emp_id,nombre,apellido,depto,emp_code) VALUES('2','Willer','Lima','Sistemas','2');
INSERT INTO personal(emp_id,nombre,apellido,depto,emp_code) VALUES('3','Eduardo','Espinoza','Post-Produccion','3');
INSERT INTO personal(emp_id,nombre,apellido,depto,emp_code) VALUES('4','Bryan','Miranda','Post-Produccion','4');
INSERT INTO personal(emp_id,nombre,apellido,depto,emp_code) VALUES('5','Jhon Cristian','Calle','Post-Produccion','5');
INSERT INTO personal(emp_id,nombre,apellido,depto,emp_code) VALUES('6','Jade Adriana','Mamani Mamani','Administracion','7');
INSERT INTO personal(emp_id,nombre,apellido,depto,emp_code) VALUES('7','Jenny Lizeth','Mamani Aduviri','Administracion','8');
INSERT INTO personal(emp_id,nombre,apellido,depto,emp_code) VALUES('8','Melanie ','Sanchez Paucara','Administracion','9');
INSERT INTO personal(emp_id,nombre,apellido,depto,emp_code) VALUES('9','Christian','Arauco','Produccion','10');
INSERT INTO personal(emp_id,nombre,apellido,depto,emp_code) VALUES('10','Angela','Mayta','Produccion','14');
INSERT INTO personal(emp_id,nombre,apellido,depto,emp_code) VALUES('11','Manuel Jose','Crespo Robles','Tecnica','19');
INSERT INTO personal(emp_id,nombre,apellido,depto,emp_code) VALUES('12','Carol','Guzman','Produccion','22');
INSERT INTO personal(emp_id,nombre,apellido,depto,emp_code) VALUES('13','Jaime','Bravo Sandoval','Planificacion','28');
INSERT INTO personal(emp_id,nombre,apellido,depto,emp_code) VALUES('14','Jhonatan','Quispe Hidalgo','Tecnica','29');
INSERT INTO personal(emp_id,nombre,apellido,depto,emp_code) VALUES('15','Boris','Flores Herrera','Comercial','30');
INSERT INTO personal(emp_id,nombre,apellido,depto,emp_code) VALUES('16','Juan Alberto','Laura Sierra','Produccion','31');
INSERT INTO personal(emp_id,nombre,apellido,depto,emp_code) VALUES('17','Alejandro','Pinedo','Gerencia','33');
INSERT INTO personal(emp_id,nombre,apellido,depto,emp_code) VALUES('18','Carlos','Chambi Yana','Produccion','35');
INSERT INTO personal(emp_id,nombre,apellido,depto,emp_code) VALUES('19','Eloy','Mayta Nina','Logistica','36');
INSERT INTO personal(emp_id,nombre,apellido,depto,emp_code) VALUES('20','Wendy Stephanie','Zambrana Monasterio','Produccion','37');
INSERT INTO personal(emp_id,nombre,apellido,depto,emp_code) VALUES('21','Wilbert','Leon Moscoso','Produccion','38');
INSERT INTO personal(emp_id,nombre,apellido,depto,emp_code) VALUES('22','Jhanira Laura','Condori','Comercial','40');
INSERT INTO personal(emp_id,nombre,apellido,depto,emp_code) VALUES('23','Jason','Beltran','Tecnica','41');
INSERT INTO personal(emp_id,nombre,apellido,depto,emp_code) VALUES('24','Paula ','Conza Sejas','Comercial','42');
INSERT INTO personal(emp_id,nombre,apellido,depto,emp_code) VALUES('25','Wendy','Limachi Copana','Produccion','45');
INSERT INTO personal(emp_id,nombre,apellido,depto,emp_code) VALUES('26','Harold Abel','Quispe Aiza','Produccion','46');
INSERT INTO personal(emp_id,nombre,apellido,depto,emp_code) VALUES('27','Veronica','Choque Gutierrez','Produccion','47');
INSERT INTO personal(emp_id,nombre,apellido,depto,emp_code) VALUES('28','Freddy','Choque Ulloa','Produccion','48');
INSERT INTO personal(emp_id,nombre,apellido,depto,emp_code) VALUES('29','Bryan Orlando','Marin Duran','Comercial','49');
INSERT INTO personal(emp_id,nombre,apellido,depto,emp_code) VALUES('31','Wilmer','Paucara Jimenez','Prensa','51');
INSERT INTO personal(emp_id,nombre,apellido,depto,emp_code) VALUES('36','Beimar','Quispe Medrano','Produccion','62');
INSERT INTO personal(emp_id,nombre,apellido,depto,emp_code) VALUES('37','Barbara','Palacios Mendoza','Produccion','68');
INSERT INTO personal(emp_id,nombre,depto,emp_code) VALUES('38','Rafael','Produccion','69');
INSERT INTO personal(emp_id,nombre,depto,emp_code) VALUES('39','Betty','Logistica','18');
INSERT INTO personal(emp_id,nombre,apellido,depto,emp_code) VALUES('40','Henry','Aruquipa Jarandilla','Post-Produccion','70');
INSERT INTO personal(emp_id,nombre,apellido,depto,emp_code) VALUES('41','Ruth','Huanca Atahuachi','Produccion','71');
INSERT INTO personal(emp_id,nombre,apellido,depto,emp_code) VALUES('42','Gherabi','Ramos Mendoza','Produccion','72');
INSERT INTO personal(emp_id,nombre,apellido,depto,emp_code) VALUES('46','Daniel','Juarez','Produccion','25');
INSERT INTO personal(emp_id,nombre,apellido,depto,emp_code) VALUES('51','Belen Naydelin','Chino Quisbert','Produccion','15');
INSERT INTO personal(emp_id,nombre,apellido,depto,emp_code) VALUES('55','Jonatan','Quinto Lima','Produccion','26');
INSERT INTO personal(emp_id,nombre,apellido,depto,emp_code) VALUES('56','Cesar','Marino Sanchez','Post-Produccion','27');
INSERT INTO personal(emp_id,nombre,apellido,depto,emp_code) VALUES('57','Katerine','Cabrera Rojas','Prensa','32');
INSERT INTO personal(emp_id,nombre,apellido,depto,emp_code) VALUES('60','Jazmin','Quisbert Sanchez','Produccion','74');
INSERT INTO personal(emp_id,nombre,apellido,depto,emp_code) VALUES('61','Vladimir','Condori','Prensa','75');
INSERT INTO personal(emp_id,nombre,apellido,depto,emp_code) VALUES('62','Alfredo','Yana','Sistemas','100');
INSERT INTO personal(emp_id,nombre,apellido,depto,emp_code) VALUES('63','Ivan','Quispe Chambi','Produccion','101');
INSERT INTO personal(emp_id,nombre,apellido,depto,emp_code) VALUES('64','Janny Jhanitza','Caceres Alanoca','Produccion','102');
INSERT INTO personal(emp_id,nombre,apellido,depto,emp_code) VALUES('65','Giovanna ','Cruz','Produccion','103');
INSERT INTO personal(emp_id,nombre,apellido,depto,emp_code) VALUES('66','Leyla','Calle Colque','Produccion','104');
INSERT INTO personal(emp_id,nombre,apellido,depto,emp_code) VALUES('67','Kati','Conde','Produccion','105');
INSERT INTO personal(emp_id,nombre,apellido,depto,emp_code) VALUES('68','Andrea Mayden','Carani Calderon','Produccion','106');
INSERT INTO personal(emp_id,nombre,apellido,depto,emp_code) VALUES('69','Ambar','Villanueva','Produccion','107');
INSERT INTO personal(emp_id,nombre,apellido,depto,emp_code) VALUES('70','Rosmery','Mamani','Produccion','108');
INSERT INTO personal(emp_id,nombre,apellido,depto,emp_code) VALUES('71','Cinthia','Huayhua','Producion','170');
INSERT INTO personal(emp_id,nombre,apellido,depto,emp_code) VALUES('72','Celia','Lisarraga','Comercial','76');
INSERT INTO personal(emp_id,nombre,apellido,depto,emp_code) VALUES('73','Adrian','Pillco','Comercial','77');
INSERT INTO personal(emp_id,nombre,apellido,depto,emp_code) VALUES('74','Viviana','Machaca','Produccion','109');
INSERT INTO personal(emp_id,nombre,apellido,depto,emp_code) VALUES('75','Willy','Quito','Prensa','110');
INSERT INTO personal(emp_id,nombre,apellido,emp_code) VALUES('76','Keila','Huanca Alvarado','78');